# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4bf74161198fc899d8bccd99e7525d848b36bd6ac23e3786a0db82d52b6615357b700be4ab432947dc6b42fd8dea6b7d1b6ad3ac7f823042f03049c1ae689e6

test:
  secret_key_base: f7861b21f41bc736be35b5adc0fc2056dc4d7b29be29b1bb9dbaa8d5177307c5ed786070ad869b932aa4ee7fdc52c0d35746604268f631d3fdc3b36cd557b9f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
